source "https://rubygems.org"

gem "activerecord", "~> 4.1"
gem "pg", "~> 0.21"
gem "rake"
gem "sinatra", "~> 1.4"
gem "sinatra-activerecord", "~> 2.0"
gem "sinatra-contrib"
gem "sinatra-flash"
gem "mysql2"
gem "mysql2-cs-bind"
